### ISSUE TITLE
海滨乱斗报错

### ISSUE THREAD

**Issue by nitnoQAQ** [sophisticate9008/fight#19]
输入支持目标和应援金后无反应

【群主】nitnoQAQ 2022/11/18 17:13:27
海滨乱斗

【管理员】是真寻吖~ 2022/11/18 17:13:30
随机到的两名英桀是
格蕾修  爱莉希雅
胜率分别为0.11  0.89
 获胜获得金币乘数分别为9.14  1.12
请选择支持目标和应援金, 0为前 1为后, 两个参数空格隔开

【群主】nitnoQAQ 2022/11/18 17:13:33
1 100

: Message -1728231232 from 3509732673@[群:939356563] "海滨乱斗"
11-18 17:13:26 [INFO] nonebot | Event will be handled by Matcher(type='message',
 module=plugins.mute)
11-18 17:13:26 [INFO] nonebot | Event will be handled by Matcher(type='message',
 module=plugins.black_word)
11-18 17:13:27 [INFO] nonebot | Event will be handled by Matcher(type='message',
 module=basic_plugins.chat_history.chat_message)
11-18 17:13:27 [INFO] nonebot | Event will be handled by Matcher(type='message',
 module=plugins.parse_bilibili_json)
11-18 17:13:27 [INFO] nonebot | Matcher(type='message', module=plugins.black_wor
d) running complete
11-18 17:13:27 [INFO] nonebot | Matcher(type='message', module=plugins.mute) run
ning complete
11-18 17:13:27 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bil
ibili_json) running complete
11-18 17:13:27 [INFO] nonebot | Matcher(type='message', module=basic_plugins.cha
t_history.chat_message) running complete
11-18 17:13:27 [INFO] nonebot | Event will be handled by Matcher(type='message',
 module=extensive_plugin.fight)
11-18 17:13:28 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.
fight) running complete
11-18 17:13:32 [SUCCESS] nonebot | OneBot V11 399148481 | [message.group.normal]
: Message -1123314895 from 3509732673@[群:939356563] "1 100"
11-18 17:13:32 [INFO] nonebot | Event will be handled by Matcher(type='message',
 module=extensive_plugin.fight)
11-18 17:13:32 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.
fight) running complete
11-18 17:13:32 [ERROR] nonebot | Running Matcher(type='message', module=extensiv
e_plugin.fight) failed.
Traceback (most recent call last):
  File "C:\zhenxun_bot-0.1.6.4\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in
run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run
_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in
run_forever
    super().run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run
_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _r
un_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\nonebot\message.py", line 142, in _check_m
atcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\nonebot\message.py", line 186, in _run_mat
cher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\nonebot\internal\matcher.py", line 716, in
 run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\nonebot\internal\matcher.py", line 688, in
 simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 10
8, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\zhenxun_bot-0.1.6.4\extensive_plugin\fight\__init__.py", line 233, in
 _
    list_fight = stats(list_role[0], list_role[1], 1, 1, list_fight)
  File "C:\zhenxun_bot-0.1.6.4\extensive_plugin\fight\fightStats.py", line 33, i
n stats
    creates(list_info, left, right, n, isDisplay)
  File "C:\zhenxun_bot-0.1.6.4\extensive_plugin\fight\fightCreate.py", line 24,
in creates
    fight( left1, right1, isDisplay, two)
  File "C:\zhenxun_bot-0.1.6.4\extensive_plugin\fight\fightFrame.py", line 309,
in fight
    image_add_text(count, txts,  text_color=(0, 0, 0), text_size=12)
  File "C:\zhenxun_bot-0.1.6.4\extensive_plugin\fight\picture_make.py", line 54,
 in image_add_text
    fontStyle = ImageFont.truetype(fight_ttf, text_size, encoding="utf-8")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\PIL\ImageFont.py", line 959, in truetype
    return freetype(font)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\PIL\ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-
bot-Gl9RUuSI-py3.10\lib\site-packages\PIL\ImageFont.py", line 247, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by sophisticate9008** [comment]
随便复制一份字体改为yuanshen.ttf

**Comment by nitnoQAQ** [comment]
> 

已解决，非常感谢
